services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # project_management:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

volumes:
  postgres_data:
