# Generated by Django 5.1.6 on 2025-03-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='on_trail',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
    ]
